#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: c
sudo: false

env:
    global:
    - BYOND_MAJOR="510"
    - BYOND_MINOR="1345"
    matrix:
    - DM_MAPFILE="tgstation2"
  
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip
  
install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - chmod +x tools/check_filedirs.sh
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
  
notifications:
  slack: hippiestation13:szQihSePHinCZboi1o4GaLCp

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' _maps/**/*.dmm)
  - md5sum -c - <<< "29d5a6e23d172846354505e60ecfe7e7 *html/changelogs/example.yml"
  - tools/check_filedirs.sh tgstation.dme
  - python tools/ss13_genchangelog.py html/changelog.html html/changelogs
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme
