language: generic
sudo: false

env:
    global:
    - BYOND_MAJOR="509"
    - BYOND_MINOR="1300"
    matrix:
    - DM_MAPFILE="tgstation2"
  
cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip
  
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION
  - npm install -g gulp-cli
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - cd tgui && npm install && cd ..
  - chmod +x tools/check_filedirs.sh
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
  
notifications:
  slack: hippiestation13:szQihSePHinCZboi1o4GaLCp

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' _maps/**/*.dmm)
  - md5sum -c - <<< "29d5a6e23d172846354505e60ecfe7e7 *html/changelogs/example.yml"
  - tools/check_filedirs.sh tgstation.dme
  - cd tgui && gulp && cd ..
  - python tools/ss13_genchangelog.py html/changelog.html html/changelogs
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme
